apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aabedraba/kube-test-devops.git
    targetRevision: HEAD
    path: kubernetes
    kustomize:
      images:
        - "asia-south1-docker.pkg.dev/devrel-341608/kube-test/backend:0cb6d40"
        - "asia-south1-docker.pkg.dev/devrel-341608/kube-test/frontend:0cb6d40"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-test-app-tests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aabedraba/kube-test.git
    targetRevision: HEAD
    path: tests
    plugin:
      name: testkube
  destination:
    server: https://kubernetes.default.svc
    namespace: testkube

