apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend.yaml
  - frontend.yaml
  - application.yaml

images:
  - name: backend-image
    newName: asia-south1-docker.pkg.dev/PROJECT_ID/kube-test/backend
    newTag: SHORT_SHA
  - name: frontend-image
    newName: asia-south1-docker.pkg.dev/PROJECT_ID/kube-test/frontend
    newTag: SHORT_SHA