apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend.yaml
  - frontend.yaml
  - application.yaml

images:
  - name: backend-image
    newName: asia-south1-docker.pkg.dev/devrel-341608/kube-test/backend
    newTag: 951ae81
  - name: frontend-image
    newName: asia-south1-docker.pkg.dev/devrel-341608/kube-test/frontend
    newTag: 951ae81